include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # Web
    - 'web/**'
    # Build
    - 'build/**'
    # Generated code
    - 'lib/**.g.dart'
    - 'lib/**.freezed.dart'
    - 'lib/generated_plugin_registrant.dart'
    - 'lib/l10n/**'
    - '.test_coverage.dart'
    # Assets
    - 'assets/**'

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    # Ignore
    # invalid_annotation_target: ignore ???

    # Info
    todo: info
    directives_ordering: info
    always_declare_return_types: info

    # Warning
    avoid_slow_async_io: warning
    cancel_subscriptions: error
    close_sinks: error
    empty_catches: warning
    flutter_style_todos: warning
    no_logic_in_create_state: warning
    prefer_relative_imports: warning
    unsafe_html: warning

    # Error
    avoid_relative_lib_imports: error
    avoid_types_as_parameter_names: error
    valid_regexps: error

linter:
  rules:
    #
    # Error Rules
    #

    # always_use_package_imports: true # DO avoid relative imports for files in lib/.
    # avoid_dynamic_calls: true
    # avoid_empty_else: true # [core]
    # avoid_print: true # [flutter]
    # avoid_relative_lib_imports: true # [core]
    avoid_slow_async_io: true
    avoid_type_to_string: true
    # avoid_types_as_parameter_names: true # [core]
    # avoid_web_libraries_in_flutter: true # [flutter]
    cancel_subscriptions: true
    close_sinks: true
    collection_methods_unrelated_type: true
    comment_references: true
    # control_flow_in_finally: true # [recommended]
    # diagnostic_describe_all_properties: true
    # discarded_futures: true # DON'T invoke asynchronous functions in non-async blocks.
    # empty_statements: true # [recommended]
    # hash_and_equals: true # [core]
    invalid_case_patterns: true
    # iterable_contains_unrelated_type: true # [core]
    # list_remove_unrelated_type: true # [core]
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    # no_duplicate_case_values: true # [core]
    # no_logic_in_create_state: true # [flutter]
    # prefer_relative_imports: true
    # prefer_void_to_null: true # [recommended]
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    # unrelated_type_equality_checks: true # [core]
    unsafe_html: true
    # use_build_context_synchronously: true # [flutter]
    # use_key_in_widget_constructors: true # [flutter]
    # valid_regexps: true # [core]

    #
    # Style Rules
    #

    always_declare_return_types: true
    # always_put_control_body_on_new_line: true
    # always_put_required_named_parameters_first: true
    # always_specify_types: true
    # annotate_overrides: true # [recommended]
    # avoid_annotating_with_dynamic: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    avoid_classes_with_only_static_members: true
    avoid_double_and_int_checks: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_final_parameters: true
    # avoid_function_literals_in_foreach_calls: true # [recommended]
    avoid_implementing_value_types: true
    # avoid_init_to_null: true # [recommended]
    avoid_js_rounded_ints: true
    avoid_multiple_declarations_per_line: true
    # avoid_null_checks_in_equality_operators: true # [recommended]
    # avoid_positional_boolean_parameters: true
    # avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true # DON'T pass an argument that matches the corresponding parameter's default value.
    # avoid_renaming_method_parameters: true # [recommended]
    # avoid_return_types_on_setters: true # [recommended]
    # avoid_returning_null_for_void: true # [recommended]
    avoid_returning_this: true
    avoid_setters_without_getters: true
    # avoid_shadowing_type_parameters: true # [core]
    # avoid_single_cascade_in_expression_statements: true # [recommended]
    avoid_types_on_closure_parameters: true
    # avoid_unnecessary_containers: true # [flutter]
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    # await_only_futures: true # [core]
    # camel_case_extensions: true # [core]
    # camel_case_types: true # [core]
    cascade_invocations: true
    cast_nullable_to_non_nullable: true # DON'T cast a nullable value to a non nullable type.
    combinators_ordering: true # DO sort combinator names alphabetically.
    conditional_uri_does_not_exist: true
    # constant_identifier_names: true # [recommended]
    # curly_braces_in_flow_control_structures: true # [core]
    dangling_library_doc_comments: true
    deprecated_consistency: true
    directives_ordering: true
    # do_not_use_environment: true
    # empty_catches: true # [core]
    # empty_constructor_bodies: true # [recommended]
    eol_at_end_of_file: true
    # exhaustive_cases: true # [recommended]
    # file_names: true # [core]
    flutter_style_todos: true
    # implementation_imports: true # [recommended]
    implicit_call_tearoffs: true # DO Explicitly tear off .call methods from objects when assigning to a Function type.
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    library_annotations: true
    # library_names: true # [recommended]
    # library_prefixes: true # [recommended]
    # library_private_types_in_public_api: true # [recommended]
    lines_longer_than_80_chars: true
    missing_whitespace_between_adjacent_strings: true
    no_default_cases: true
    # no_leading_underscores_for_library_prefixes: true # [recommended]
    # no_leading_underscores_for_local_identifiers: true # [recommended]
    no_runtimeType_toString: true
    # non_constant_identifier_names: true # [core]
    noop_primitive_operations: true
    # null_check_on_nullable_type_parameter: true # [core]
    # null_closures: true # [recommended]
    omit_local_variable_types: true
    one_member_abstracts: true
    only_throw_errors: true
    # overridden_fields: true # [recommended]
    package_api_docs: true # DO provide doc comments for all public APIs.
    # package_prefixed_library_names: true # [core]
    parameter_assignments: true
    # prefer_adjacent_string_concatenation: true # [recommended]
    prefer_asserts_in_initializer_lists: true
    # prefer_asserts_with_message: true
    # prefer_collection_literals: true # [recommended]
    # prefer_conditional_assignment: true # [recommended]
    prefer_const_constructors: true # [flutter]
    prefer_const_constructors_in_immutables: true # [flutter]
    prefer_const_declarations: true # [flutter]
    prefer_const_literals_to_create_immutables: true # [flutter]
    prefer_constructors_over_static_methods: true
    # prefer_contains: true # [recommended]
    # prefer_double_quotes: true
    prefer_expression_function_bodies: true
    # prefer_final_fields: true # [recommended]
    prefer_final_in_for_each: true
    prefer_final_locals: true
    # prefer_final_parameters: true
    # prefer_for_elements_to_map_fromIterable: true # [recommended]
    prefer_foreach: true
    # prefer_function_declarations_over_variables: true # [recommended]
    # prefer_generic_function_type_aliases: true # [core]
    prefer_if_elements_to_conditional_expressions: true
    # prefer_if_null_operators: true # [recommended]
    # prefer_initializing_formals: true # [recommended]
    # prefer_inlined_adds: true # [recommended]
    prefer_int_literals: true
    # prefer_interpolation_to_compose_strings: true # [recommended]
    # prefer_is_empty: true # [core]
    # prefer_is_not_empty: true # [core]
    # prefer_is_not_operator: true # [recommended]
    # prefer_iterable_whereType: true # [core]
    prefer_mixin: true
    prefer_null_aware_method_calls: true
    # prefer_null_aware_operators: true # [recommended]
    prefer_single_quotes: true
    # prefer_spread_collections: true # [recommended]
    # prefer_typing_uninitialized_variables: true # [core]
    # provide_deprecation_message: true # [core]
    # public_member_api_docs: true # DO document all public members.
    # recursive_getters: true # [recommended]
    require_trailing_commas: true
    # sized_box_for_whitespace: true # [flutter]
    sized_box_shrink_expand: true
    # slash_for_doc_comments: true # [recommended]
    # sort_child_properties_last: true # [flutter]
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: true
    # type_init_formals: true # [recommended]
    unawaited_futures: true # DO await functions that return a Future inside of an async function body.
    unnecessary_await_in_return: true
    # unnecessary_brace_in_string_interps: true # [recommended]
    unnecessary_breaks: true
    # unnecessary_const: true # [recommended]
    # unnecessary_constructor_name: true # [recommended]
    # unnecessary_final: true # Use var, not final, when declaring local variables.
    # unnecessary_getters_setters: true # [recommended]
    unnecessary_lambdas: true
    # unnecessary_late: true # [recommended]
    unnecessary_library_directive: true
    # unnecessary_new: true # [recommended]
    # unnecessary_null_aware_assignments: true # [recommended]
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_null_checks: true
    # unnecessary_null_in_if_null_operators: true # [recommended]
    # unnecessary_nullable_for_final_variable_declarations: true # [recommended]
    # unnecessary_overrides: true # [core]
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    # unnecessary_string_escapes: true # [recommended]
    # unnecessary_string_interpolations: true # [recommended]
    # unnecessary_this: true # [recommended]
    unnecessary_to_list_in_spreads: true
    unreachable_from_main: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    # use_full_hex_values_for_flutter_colors: true # [flutter]
    # use_function_type_syntax_for_parameters: true # [recommended]
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    # use_rethrow_when_possible: true # [recommended]
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_string_in_part_of_directives: true
    use_super_parameters: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true
    # void_checks: true # [core]

    #
    # Pub Rules
    #

    # depend_on_referenced_packages: true # [core]
    # package_names: true # [recommended]
    secure_pubspec_urls: true
    sort_pub_dependencies: true
