name: flutter_app_architecture_overview
description: Flutter App Architecture Overview.
publish_to: 'none'

version: 1.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  app_scope:
    path: packages/app_scope
  auth:
    path: packages/auth
  common:
    path: packages/common
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  user_scope:
    path: packages/user_scope

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
